#!/bin/sh

# =========================================================================
# =========================================================================
#
#	lamps-run
#	  Create & Run the LAMPS containers the first time.
#
# =========================================================================
#
# @author Jay Wheeler.
# @version 0.1.0
# @copyright © 2017. EarthWalk Software.
# @license Licensed under the Academic Free License version 3.0
# @package LAMPS
# @subpackage lamps-run
#
# =========================================================================
#
#	Copyright © 2017. EarthWalk Software
#	Licensed under the Academic Free License, version 3.0.
#
#	Refer to the file named License.txt provided with the source,
#	or from
#
#		http://opensource.org/licenses/academic.php
#
# =========================================================================
# =========================================================================
if [ ! -n "$LCONFIG" ]
then
    if [ ! -f "/var/local/lamps/.lamps" ]
    then
        RUNFROM=$( cd $(dirname $0) ; pwd -P )
        if [ ! -f "$RUNFROM"/.lamps" ] then
        then
            echo "Unable to find configuration file"
            exit 99
        fi
        LCONFIG=$RUNFROM/.lamps
    else
      LCONFIG="/var/local/lamps/.lamps"
    fi
fi

echo "$LCONFIG"
. $LCONFIG
echo "$LAMPS_USER_NAME"


