#!/bin/sh

# =========================================================================
# =========================================================================
#
#	lamps-restart
#	  Restart the LAMPS containers.
#
# =========================================================================
#
# @author Jay Wheeler.
# @version 0.1.0
# @copyright © 2017. EarthWalk Software.
# @license Licensed under the Academic Free License version 3.0
# @package LAMPS
# @subpackage lamps-restart
#
# =========================================================================
#
#	Copyright © 2017. EarthWalk Software
#	Licensed under the Academic Free License, version 3.0.
#
#	Refer to the file named License.txt provided with the source,
#	or from
#
#		http://opensource.org/licenses/academic.php
#
# =========================================================================
# =========================================================================

docker restart apache
docker restart apache-php5
docker restart apache-svn
docker restart mariadb
docker restart phpmyadmin
