#!/bin/sh

# =========================================================================
# =========================================================================
#
#	lamps-rm
#	  Remove the LAMPS containers.
#
# =========================================================================
#
# @author Jay Wheeler.
# @version 0.1.0
# @copyright © 2017. EarthWalk Software.
# @license Licensed under the Academic Free License version 3.0
# @package LAMPS
# @subpackage lamps-rm
#
# =========================================================================
#
#	Copyright © 2017. EarthWalk Software
#	Licensed under the Academic Free License, version 3.0.
#
#	Refer to the file named License.txt provided with the source,
#	or from
#
#		http://opensource.org/licenses/academic.php
#
# =========================================================================
# =========================================================================

docker rm apache
docker rm apache-php5
docker rm apache-svn
docker rm mariadb
docker rm phpmyadmin
