#!/bin/sh

# =========================================================================
# =========================================================================
#
#	lamps-init
#	  Create & Run the LAMPS containers the first time.
#
# =========================================================================
#
# @author Jay Wheeler.
# @version 0.1.0
# @copyright © 2017. EarthWalk Software.
# @license Licensed under the Academic Free License version 3.0
# @package LAMPS
# @subpackage lamps-init
#
# =========================================================================
#
#	Copyright © 2017. EarthWalk Software
#	Licensed under the Academic Free License, version 3.0.
#
#	Refer to the file named License.txt provided with the source,
#	or from
#
#		http://opensource.org/licenses/academic.php
#
# =========================================================================
# =========================================================================
if [ ! -n "$LCONFIG" ]
then
    if [ ! -f "/var/local/lamps/.lamps" ]
    then
        echo "Unable to find configuration file"
        exit 99
    fi

    LCONFIG="/var/local/lamps/.lamps"
fi

echo "Configuration: $LCONFIG"

. $LCONFIG

# =========================================================================
# =========================================================================

docker run -d \
           --name=apache \
           --restart unless-stopped \
           -p $LAMPS_APACHE_HTTP:80 \
           -p $LAMPS_APACHE_HTTPS:443\
           -v $LAMPS_DATA/apache:/web \
       apache-php7:latest
#
docker run -d \
           --name=apache-php5 \
           --restart unless-stopped \
           -p $LAMPS_APACHE_5_HTTP:80 \
           -p $LAMPS_APACHE_5_HTTPS:443 \
           -v $LAMPS_DATA/apache-php5:/web \
       apache-php5:latest
#
docker run -d \
           --name=apache-svn \
           --restart unless-stopped \
           -p $LAMPS_SVN_HTTP:80 \
           -e SVN_USER=$LAMPS_USER_NAME \
           -e SVN_PASS=$LAMPS_USER_PASS \
           -v $LAMPS_DATA/apache-svn/svn:/svn \
       apache-svn:latest
#
docker run -d \
           --name=mariadb \
           --restart unless-stopped \
           -p $LAMPS_MARIADB:3306 \
           -e MARIADB_DATABASE=$LAMPS_DB \
           -e MARIADB_ROOT_PASSWORD=$LAMPS_ROOT_PASS \
           -e MARIADB_REMOTE_ROOT=$LAMPS_ROOT \
           -e MARIADB_USER=$LAMPS_USER_NAME \
           -e MARIADB_PASSWORD=$LAMPS_USER_PASS \
           -v $LAMPS_DATA/mariadb:/data \
       mariadb:latest
#
docker run -d \
           --name phpmyadmin \
           --restart unless-stopped \
           --link mariadb:db \
           -p $LAMPS_PHPMYADMIN:80 \
           -e MYSQL_ROOT_PASSWORD=$LAMPS_ROOT_PASS \
       phpmyadmin:latest
#
