#!/bin/sh

# =========================================================================
# =========================================================================
#
#	lamps-rmipulls
#	  Remove the LAMPS pulled images.
#
# =========================================================================
#
# @author Jay Wheeler.
# @version 0.1.0
# @copyright © 2017. EarthWalk Software.
# @license Licensed under the Academic Free License version 3.0
# @package LAMPS
# @subpackage lamps-rmipulls
#
# =========================================================================
#
#	Copyright © 2017. EarthWalk Software
#	Licensed under the Academic Free License, version 3.0.
#
#	Refer to the file named License.txt provided with the source,
#	or from
#
#		http://opensource.org/licenses/academic.php
#
# =========================================================================
# =========================================================================

docker rmi nimmis/alpine-apache-php7:latest
docker rmi nimmis/alpine-apache-php5:latest
docker rmi nimmis/alpine-mariadb:latest
docker rmi earthwalksoftware/alpine-svn:latest
docker rmi phpmyadmin/phpmyadmin:latest
