#!/bin/sh

# =========================================================================
# =========================================================================
#
#	lamps-pull
#	  Pull the LAMPS images form Docker Hub.
#
# =========================================================================
#
# @author Jay Wheeler.
# @version 0.1.0
# @copyright © 2017. EarthWalk Software.
# @license Licensed under the Academic Free License version 3.0
# @package LAMPS
# @subpackage lamps-pull
#
# =========================================================================
#
#	Copyright © 2017. EarthWalk Software
#	Licensed under the Academic Free License, version 3.0.
#
#	Refer to the file named License.txt provided with the source,
#	or from
#
#		http://opensource.org/licenses/academic.php
#
# =========================================================================
# =========================================================================

docker pull nimmis/alpine-apache-php7:latest
docker pull nimmis/alpine-apache-php5:latest
docker pull nimmis/alpine-mariadb:latest
docker pull earthwalksoftware/alpine-svn:latest
docker pull phpmyadmin/phpmyadmin:latest
